# Generated by Django 4.1 on 2022-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default='No ingredients provided'),
            preserve_default=False,
        ),
    ]
